{% set version = "18.20.0" %}

package:
  name: python-kubernetes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kubernetes/kubernetes-{{ version }}.tar.gz
  sha256: 0c72d00e7883375bd39ae99758425f5e6cb86388417cf7cc84305c211b2192cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - certifi >=14.05.14
    - google-auth >=1.0.1
    - python-dateutil >=2.5.3
    - pyyaml >=3.12
    - requests
    - requests-oauthlib
    - setuptools >=21.0.0
    - six >=1.9.0
    - urllib3 >=1.24.2
    - websocket-client >=0.32.0,!=0.40.0,!=0.41.*,!=0.42.*

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kubernetes
    - kubernetes.client
    - kubernetes.client.apis
    - kubernetes.client.models
    - kubernetes.config
    - kubernetes.watch

about:
  home: https://github.com/kubernetes-incubator/client-python
  license: Apache-2.0
  summary: The official Kubernetes python client.
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/kubernetes-incubator/client-python

extra:
  recipe-maintainers:
    - johanneskoester
    - ocefpaf
