{% set version = "12.0.0" %}

package:
  name: python-kubernetes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kubernetes/kubernetes-{{ version }}.tar.gz
  sha256: 72f095a1cd593401ff26b3b8d71749340394ca6d8413770ea28ce18efd5bcf4c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - certifi >=14.05.14
    - six >=1.9.0
    - python-dateutil >=2.5.3
    - setuptools >=21.0.0
    - urllib3 >=1.23
    - pyyaml >=3.12
    - google-auth >=1.0.1
    - websocket-client >=0.32.0,!=0.40.0,!=0.41.*,!=0.42.*
    - requests
    - requests-oauthlib
    - adal >=1.0.2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kubernetes
    - kubernetes.client
    - kubernetes.client.apis
    - kubernetes.client.models
    - kubernetes.config
    - kubernetes.watch

about:
  home: https://github.com/kubernetes-incubator/client-python
  license: Apache-2.0
  summary: The official Kubernetes python client.
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/kubernetes-incubator/client-python

extra:
  recipe-maintainers:
    - johanneskoester
    - ocefpaf
