schema_version: 1

context:
  version: "37.0.1"

package:
  name: python-kubernetes
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/k/kubernetes/kubernetes-${{ version }}.tar.gz
  sha256: e41db0a95615c2388680a2d556df33fd0f27a5717c9b5df5857e475c196c2f10

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - certifi >=14.05.14
    - python-dateutil >=2.8.2
    - pyyaml >=6.0.3
    - websocket-client >=0.32.0,!=0.40.0,!=0.41.*,!=0.42.*
    - requests
    - requests-oauthlib
    - urllib3 >=2.8.0,<3.0.0
    - durationpy >=0.11
    - aiohttp <4.0.0,>=3.14.3
    - pydantic >=2.13.5
    - typing_extensions >=4.16.0
    - certifi >=2026.7.22
    - aiohttp-retry >=2.9.1
tests:
  - python:
      imports:
        - kubernetes
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: Kubernetes python client
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/kubernetes-client/python

extra:
  recipe-maintainers:
    - johanneskoester
    - ocefpaf
